### ISSUE TITLE
LoadH5Seurat error: Too many values for levels provided

### ISSUE THREAD

**Issue by carcinas** [mojaveazure/seurat-disk#77]
I am able to trying to convert anndata object from scanpy (h5ad) to h5seurat to seurat object.

I can convert data.h5ad to h5seurat format using Convert().

However, when I try to run

`seurat_object <- LoadH5Seurat("data.h5seurat")
`
I get the following error: 

```
Validating h5Seurat file
Initializing RNA with counts
Adding feature-level metadata for RNA
Adding reduction pca
Adding cell embeddings for pca
Adding feature loadings for pca
Adding miscellaneous information for pca
Adding reduction umap
Adding cell embeddings for umap
Adding miscellaneous information for umap
Adding command information
Adding cell-level metadata
Error: Too many values for levels provided
```
Is there any solution to this? Thanks.

**Comment by Tycooner** [comment]
the same issue,  want help!!!!

**Comment by fly4all** [comment]
same issue, please help!

**Comment by vercanie** [comment]
In case someone finds it helpful, I was able to solve the issue by reducing the number of columns in the metadata of the original .h5ad file. I'm not sure what was causing the error, so it might not help in all cases. If you want to give it a try: 
`adata.obs = adata.obs[['column_to_keep1','column_to_keep2','column_to_keep3']]`

**Comment by btrspg** [comment]
> In case someone finds it helpful, I was able to solve the issue by reducing the number of columns in the metadata of the original .h5ad file. I'm not sure what was causing the error, so it might not help in all cases. If you want to give it a try:
> `adata.obs = adata.obs[['column_to_keep1','column_to_keep2','column_to_keep3']]`

Not worked for me.

**Comment by Wenfei-Sun** [comment]
same issue, please help.

>>> for col in adata.obs.columns: adata.obs[col]=adata.obs[col].cat.add_categories("Unknown").fillna('Unknown')
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/accessor.py", line 92, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 2487, in _delegate_method
    res = method(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 1008, in add_categories
    f"new categories must not include old categories: {already_included}"
ValueError: new categories must not include old categories: {'Unknown'}

**Comment by btrspg** [comment]
Hi @Wenfei-Sun ,

Because you have already had "Unknown" item in your categories, you could modify the command to 

```
for col in adata.obs.columns:
    adata.obs[col]=adata.obs[col].cat.add_categories("selfdefinedNA").fillna('selfdefinedNA')
```

Which will solve you problem.

**Comment by galenxing** [comment]
Building off of @btrspg, the following snippet will work if not all of your columns are categorical:

```
import pandas as pd

for col in adata.obs.columns:
    if pd.api.types.is_categorical_dtype(adata.obs[col]):
        adata.obs[col]=adata.obs[col].cat.add_categories("selfdefinedNA").fillna('selfdefinedNA')
```
